# Site settings
email: jen@mommyknowsbest.co
baseurl: "https://jaythanelam.github.io/mommy-knows-best"
paginate: 10
paginate_path: "/blog/page-:num"
google_analytics: UA-67545206-1

# SEO settings
title: Mommy Knows Best
description: Jennifer Elam's online blog about being a mother, her observations of daily life, and her interactions with the products that are supposed to make it all better.
url: "http://www.mommyknowsbest.co"
twitter_username:
default_img: 'https://jaythanelam.github.io/mommy-knows-best/assets/images/mkb-logo-02.png'

# Profile settings
name: Jennifer Elam
profile_img: 'https://jaythanelam.github.io/mommy-knows-best/assets/images/tn-titans.jpg'
profile: My online blog about being a mother, my observations of daily life, and my interactions with the products that are supposed to make it all better.
social:
github:

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
